from __future__ import annotations

REPLAY_TOP_LEVEL_KEYS: tuple[str, ...] = (
    "run_id",
    "config",
    "summary",
    "events",
    "viewer",
)

VIEWER_MAP_KEYS: tuple[str, ...] = (
    "width",
    "height",
    "terrain_codes",
    "terrain_legend",
    "hydrology_primary_legend",
    "hydrology_support_bits",
    "refuge_legend",
    "hazard_legend",
    "trophic_role_legend",
    "meat_mode_legend",
    "ecology_legend",
    "terrain_counts",
    "environment_fields",
    "base_tile_fields",
)

VIEWER_AGENT_ENCODING: tuple[str, ...] = (
    "agent_id",
    "x",
    "y",
    "energy",
    "energy_ratio",
    "hydration",
    "hydration_ratio",
    "health",
    "health_ratio",
    "injury_load",
    "age",
    "energy_modifier",
    "hydration_modifier",
    "tile_vegetation",
    "tile_recovery_debt",
    "reproduction_ready",
    "trophic_role",
    "meat_mode",
    "last_damage_source",
    "water_access_reason",
    "soft_refuge_reason",
    "hydrology_support_code",
    "refuge_score",
    "matched_diet_ratio",
    "ecotype_id",
    "species_id",
)

FULL_ONLY_SUMMARY_FIELDS: tuple[str, ...] = (
    "taxonomy_mode",
    "mind_contracts",
    "species_created",
    "alive_species_count",
    "alive_species",
    "top_species",
    "speciation_events",
    "species_status_counts",
    "top_species_by_realized_animal_share",
    "top_species_by_realized_fresh_kill_share",
    "top_species_by_realized_carcass_share",
    "top_carnivore_species",
    "top_hunter_species",
    "top_scavenger_species",
)

SHARED_SUMMARY_FIELDS: tuple[str, ...] = (
    "run_id",
    "seed",
    "ticks_executed",
    "births",
    "deaths",
    "alive_agents",
    "max_agents",
    "max_agent_saturation_at_end",
    "peak_max_agent_saturation",
    "peak_alive_agents",
    "carrying_capacity",
    "extinct",
    "total_agents_seen",
    "season_at_end",
    "disturbance_at_end",
    "disturbance_strength_at_end",
    "lineages",
    "alive_lineages",
    "top_lineages",
    "reproductive_groups_end",
    "ecotypes_created",
    "alive_ecotype_count",
    "last_birth_tick",
    "field_stats",
    "terrain_counts",
    "land_tile_count",
    "habitat_state_counts_at_end",
    "hydrology_primary_counts_at_end",
    "hydrology_support_counts_at_end",
    "hydrology_primary_stats_at_end",
    "refuge_counts_at_end",
    "refuge_stats_at_end",
    "hazard_counts_at_end",
    "hazard_stats_at_end",
    "biotic_field_stats_at_end",
    "signal_field_stats_at_end",
    "fresh_kill_stats_at_end",
    "carcass_stats_at_end",
    "trophic_role_counts_at_end",
    "meat_mode_counts_at_end",
    "trophic_lifecycle",
    "reproduction_end",
    "signal_end",
    "combat_end",
    "fresh_kill_end",
    "carcass_end",
    "diet_end",
    "diet_by_trophic_role_end",
    "diet_by_meat_mode_end",
    "animal_resource_opportunity_by_meat_mode_end",
    "resource_pressure",
    "selection_heredity",
    "ecology_state_counts_at_end",
    "ecology_stats_at_end",
    "avg_max_energy_gene",
    "avg_max_health_gene",
    "avg_move_cost_gene",
    "avg_food_efficiency_gene",
    "avg_water_efficiency_gene",
    "avg_attack_power_gene",
    "avg_meat_efficiency_gene",
    "avg_carrion_bias_gene",
    "avg_live_prey_bias_gene",
    "avg_forest_affinity_gene",
    "avg_plain_affinity_gene",
    "avg_wetland_affinity_gene",
    "avg_rocky_affinity_gene",
    "avg_heat_tolerance_gene",
    "avg_historical_max_energy_gene",
    "avg_historical_max_health_gene",
    "avg_historical_move_cost_gene",
    "avg_historical_food_efficiency_gene",
    "avg_historical_water_efficiency_gene",
    "avg_historical_attack_power_gene",
    "avg_historical_meat_efficiency_gene",
    "avg_historical_carrion_bias_gene",
    "avg_historical_live_prey_bias_gene",
    "avg_historical_forest_affinity_gene",
    "avg_historical_plain_affinity_gene",
    "avg_historical_wetland_affinity_gene",
    "avg_historical_rocky_affinity_gene",
    "avg_historical_heat_tolerance_gene",
    "avg_alive_max_energy_gene",
    "avg_alive_max_health_gene",
    "avg_alive_move_cost_gene",
    "avg_alive_food_efficiency_gene",
    "avg_alive_water_efficiency_gene",
    "avg_alive_attack_power_gene",
    "avg_alive_meat_efficiency_gene",
    "avg_alive_carrion_bias_gene",
    "avg_alive_live_prey_bias_gene",
    "avg_alive_forest_affinity_gene",
    "avg_alive_plain_affinity_gene",
    "avg_alive_wetland_affinity_gene",
    "avg_alive_rocky_affinity_gene",
    "avg_alive_heat_tolerance_gene",
)


def filter_summary_fields(
    summary: dict[str, object],
    fields: tuple[str, ...],
) -> dict[str, object]:
    return {field: summary[field] for field in fields if field in summary}
